# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anatomopathology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Anatomopathology',
            },
        ),
        migrations.CreateModel(
            name='Electrolytes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Electrolytes',
            },
        ),
        migrations.CreateModel(
            name='Endocrinology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Endocrinology',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('anatomopathology_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Anatomopathology')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Animal', verbose_name="Animal's Name")),
                ('electrolytes_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Electrolytes')),
                ('endocrinology_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Endocrinology')),
            ],
            options={
                'ordering': ('date',),
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
        migrations.CreateModel(
            name='Hematology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Hematology',
            },
        ),
        migrations.CreateModel(
            name='HepaticProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Hepatic profile',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Image',
            },
        ),
        migrations.CreateModel(
            name='Microbiology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Microbiology',
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Other',
            },
        ),
        migrations.CreateModel(
            name='Parasitological',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Parasitological',
            },
        ),
        migrations.CreateModel(
            name='Proteins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Proteins',
            },
        ),
        migrations.CreateModel(
            name='RenalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Renal profile',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='hematology_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Hematology'),
        ),
        migrations.AddField(
            model_name='exam',
            name='hepatic_profile_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.HepaticProfile'),
        ),
        migrations.AddField(
            model_name='exam',
            name='image_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Image'),
        ),
        migrations.AddField(
            model_name='exam',
            name='microbiology_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Microbiology'),
        ),
        migrations.AddField(
            model_name='exam',
            name='other_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Other'),
        ),
        migrations.AddField(
            model_name='exam',
            name='parasitological_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Parasitological'),
        ),
        migrations.AddField(
            model_name='exam',
            name='proteins_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Proteins'),
        ),
        migrations.AddField(
            model_name='exam',
            name='renal_profile_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.RenalProfile'),
        ),
    ]
