# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-14 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer', models.TextField(help_text='This info will be used in the footer from a document that will be printed.', verbose_name='Footer')),
            ],
            options={
                'verbose_name': 'Document',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='images/logo/', verbose_name='Logo')),
                ('background_image', models.FileField(upload_to='images/background/', verbose_name='Background image')),
            ],
            options={
                'verbose_name': 'Image',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagination', models.IntegerField(default=10, verbose_name='Pagination')),
            ],
            options={
                'verbose_name': 'Page',
            },
        ),
    ]
