# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 15:37
from __future__ import unicode_literals

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('rg', models.CharField(blank=True, max_length=12, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, max_length=15, null=True, validators=[client.models.validate_cpf], verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('cellphone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Cell Phone')),
                ('zipcode', models.CharField(blank=True, max_length=9, null=True, verbose_name='Zip Code')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('street_complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complement')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='District')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Note')),
                ('another_responsible', models.CharField(blank=True, max_length=255, null=True, verbose_name='Another Responsible')),
                ('another_responsible_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name="Another Responsible's Phone")),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
