# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-02 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clientcontact',
            options={},
        ),
    ]
