# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-21 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ManyToManyField(to='services.ExamType'),
        ),
    ]
