# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-31 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='exam_in_consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Consultation'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='vaccine_in_consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Consultation'),
        ),
    ]
