# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-27 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinetype',
            name='vaccine_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animal.Specie'),
        ),
    ]
