# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-20 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='booster',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='lot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
