# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('services', '0002_vaccinetype_vaccine_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentRegister'),
        ),
    ]
