# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-24 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180520_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='exam_file',
            field=models.FileField(blank=True, null=True, upload_to=b'exams/'),
        ),
        migrations.AddField(
            model_name='exams',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
