# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-23 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180620_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_request',
            field=models.CharField(choices=[(b'request', 'Request of exam'), (b'annex', 'Annex of exam')], default=True, max_length=10),
        ),
    ]
