# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-26 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='temperature',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
