# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-27 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_name',
            field=models.CharField(max_length=100, verbose_name="Animal's Name"),
        ),
        migrations.AlterField(
            model_name='animal',
            name='dead',
            field=models.CharField(blank=True, choices=[(b'n', 'No'), (b'y', 'Yes')], default=b'n', max_length=1, null=True, verbose_name='Dead'),
        ),
    ]
