# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 15:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('temperature', models.CharField(blank=True, max_length=3, null=True, verbose_name='Temperature')),
                ('pulse', models.NullBooleanField(verbose_name='Pulse')),
                ('pulse_note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('respiratory_rate', models.CharField(blank=True, max_length=10, null=True, verbose_name='Respiratory Rate')),
                ('bodyweight', models.CharField(blank=True, max_length=10, null=True, verbose_name='Bodyweight')),
                ('body_condition', models.CharField(blank=True, max_length=1, null=True, verbose_name='Body Condition Score')),
                ('attitude', models.CharField(blank=True, max_length=1, null=True, verbose_name='Attitude')),
                ('attitude_note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('face', models.CharField(blank=True, max_length=1, null=True, verbose_name='Face')),
                ('face_note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('eye', models.NullBooleanField(verbose_name='Eyes')),
                ('eye_note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('ear', models.NullBooleanField(verbose_name='Ears')),
                ('ear_note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('nose', models.NullBooleanField(verbose_name='Nose')),
                ('nose_note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('hydration', models.CharField(blank=True, max_length=1, null=True, verbose_name='Skin Tenting')),
                ('mouth', models.NullBooleanField(verbose_name='Mouth')),
                ('mouth_note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('mucous_membrane', models.CharField(blank=True, max_length=1, null=True, verbose_name='Mucous Membrane')),
                ('capillary_refill_time', models.CharField(blank=True, max_length=3, null=True, verbose_name='Capillary Refill Time')),
                ('superficial_lymph_nodes', models.NullBooleanField(verbose_name='Superficial Lymph Nodes')),
                ('superficial_lymph_nodes_note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('palpable_thyroid', models.NullBooleanField(verbose_name='Palpable Thyroid')),
                ('palpable_thyroid_note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('pulmonary_auscultation', models.NullBooleanField(verbose_name='Pulmonary Auscultation')),
                ('pulmonary_auscultation_note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('cardiac_auscultation', models.NullBooleanField(verbose_name='Cardiac Auscultation')),
                ('cardiac_auscultation_note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('heart_rate', models.CharField(blank=True, max_length=10, null=True, verbose_name='Heart Rate')),
                ('abdominal_palpation', models.NullBooleanField(verbose_name='Abdominal Palpation')),
                ('abdominal_palpation_note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('coat', models.NullBooleanField(verbose_name='Coat')),
                ('coat_note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('skin', models.NullBooleanField(verbose_name='Skin')),
                ('skin_note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('musculoskeletal_system', models.NullBooleanField(verbose_name='Musculoskeletal System')),
                ('musculoskeletal_system_note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('central_and_peripheral_nervous_system', models.NullBooleanField(verbose_name='Central and Peripheral Nervous Systems')),
                ('central_and_peripheral_nervous_system_note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('additional_findings', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Animal', verbose_name="Animal's Name")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client', verbose_name='Owner')),
            ],
            options={
                'ordering': ('date',),
                'verbose_name': 'Examination',
                'verbose_name_plural': 'Examinations',
            },
        ),
    ]
