# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-13 00:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('payment', models.BooleanField(choices=[(False, 'Not paid'), (True, 'Paid')], default=False, verbose_name='Payment')),
                ('temperature', models.CharField(blank=True, max_length=3, verbose_name='Temperature')),
                ('bodyweight', models.CharField(blank=True, max_length=10, verbose_name='Bodyweight')),
                ('body_condition', models.CharField(blank=True, choices=[(b'0', '1 - Very thin'), (b'1', '2 - Underweight'), (b'2', '3 - Ideal weight'), (b'3', '4 - Overweight'), (b'4', '5 - Obese')], max_length=1, verbose_name='Body Condition Score')),
                ('hydration', models.CharField(blank=True, choices=[(b'no_dehydration', 'No dehydration'), (b'reports_loss_of_liquids', 'Less than 5% - Reports loss of liquids'), (b'mild', '5 to 6% - Mild'), (b'moderate', '7 to 9% - Moderate'), (b'severe', '10 to 12% - Severe'), (b'hypovolemic_shock', '12 to 15% - Hypovolemic shock')], max_length=25, verbose_name='Skin Tenting')),
                ('mucous_membrane', models.CharField(blank=True, choices=[(b'pink', 'Pink'), (b'blue', 'Blue'), (b'pale', 'Pale'), (b'icteric', 'Icteric'), (b'congested', 'Congested')], max_length=10, verbose_name='Mucous Membrane')),
                ('palpable_thyroid', models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'abnormal', 'Abnormal')], max_length=10, verbose_name='Palpable Thyroid')),
                ('palpable_thyroid_note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('auscultation', models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'abnormal', 'Abnormal')], max_length=10, verbose_name='Auscultation')),
                ('auscultation_note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('abdominal_palpation', models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'abnormal', 'Abnormal')], max_length=10, verbose_name='Abdominal Palpation')),
                ('abdominal_palpation_note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('additional_findings', models.TextField(blank=True, verbose_name='Note')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Animal', verbose_name="Animal's Name")),
            ],
            options={
                'ordering': ('date',),
                'verbose_name': 'Examination',
                'verbose_name_plural': 'Examinations',
            },
        ),
        migrations.CreateModel(
            name='ExaminationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Examination',
                'verbose_name_plural': 'Examinations',
            },
        ),
        migrations.AddField(
            model_name='examination',
            name='examination_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physical_examination.ExaminationType', verbose_name='Type'),
        ),
    ]
