# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-04 01:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('temperature', models.CharField(blank=True, max_length=3, verbose_name='Temperature')),
                ('pulse', models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'abnormal', 'Abnormal')], max_length=10, verbose_name='Pulse')),
                ('pulse_note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('respiratory_rate', models.CharField(blank=True, max_length=10, verbose_name='Respiratory Rate')),
                ('bodyweight', models.CharField(blank=True, max_length=10, verbose_name='Bodyweight')),
                ('body_condition', models.CharField(blank=True, choices=[(b'0', '1 - Very thin'), (b'1', '2 - Underweight'), (b'2', '3 - Ideal weight'), (b'3', '4 - Overweight'), (b'4', '5 - Obese')], max_length=1, verbose_name='Body Condition Score')),
                ('attitude', models.CharField(blank=True, choices=[(b'bright_and_alert', 'Bright and Alert'), (b'quiet_but_alert', 'Quiet but Alert'), (b'lethargic', 'Lethargic'), (b'dull', 'Dull'), (b'hyperactive', 'Hyperactive'), (b'other', 'Other')], max_length=20, verbose_name='Attitude')),
                ('attitude_note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('face', models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'head_tilt', 'Head tilt'), (b'abnormal', 'Abnormal')], max_length=10, verbose_name='Face')),
                ('face_note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('eye', models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'abnormal', 'Abnormal')], max_length=10, verbose_name='Eye')),
                ('eye_note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('ear', models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'abnormal', 'Abnormal')], max_length=10, verbose_name='Ear')),
                ('ear_note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('nose', models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'abnormal', 'Abnormal')], max_length=10, verbose_name='Nose')),
                ('nose_note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('hydration', models.CharField(blank=True, choices=[(b'no_dehydration', 'No dehydration'), (b'reports_loss_of_liquids', 'Less than 5% - Reports loss of liquids'), (b'mild', '5 to 6% - Mild'), (b'moderate', '7 to 9% - Moderate'), (b'severe', '10 to 12% - Severe'), (b'hypovolemic_shock', '12 to 15% - Hypovolemic shock')], max_length=25, verbose_name='Skin Tenting')),
                ('mouth', models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'abnormal', 'Abnormal')], max_length=10, verbose_name='Mouth')),
                ('mouth_note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('mucous_membrane', models.CharField(blank=True, choices=[(b'pink', 'Pink'), (b'blue', 'Blue'), (b'pale', 'Pale'), (b'icteric', 'Icteric'), (b'congested', 'Congested')], max_length=10, verbose_name='Mucous Membrane')),
                ('capillary_refill_time', models.CharField(blank=True, max_length=3, verbose_name='Capillary Refill Time')),
                ('superficial_lymph_nodes', models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'abnormal', 'Abnormal')], max_length=10, verbose_name='Superficial Lymph Nodes')),
                ('superficial_lymph_nodes_note', models.CharField(blank=True, max_length=100, verbose_name='Note')),
                ('palpable_thyroid', models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'abnormal', 'Abnormal')], max_length=10, verbose_name='Palpable Thyroid')),
                ('palpable_thyroid_note', models.CharField(blank=True, max_length=100, verbose_name='Note')),
                ('pulmonary_auscultation', models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'abnormal', 'Abnormal')], max_length=10, verbose_name='Pulmonary Auscultation')),
                ('pulmonary_auscultation_note', models.CharField(blank=True, max_length=100, verbose_name='Note')),
                ('cardiac_auscultation', models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'abnormal', 'Abnormal')], max_length=10, verbose_name='Cardiac Auscultation')),
                ('cardiac_auscultation_note', models.CharField(blank=True, max_length=100, verbose_name='Note')),
                ('heart_rate', models.CharField(blank=True, max_length=10, verbose_name='Heart Rate')),
                ('abdominal_palpation', models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'abnormal', 'Abnormal')], max_length=10, verbose_name='Abdominal Palpation')),
                ('abdominal_palpation_note', models.CharField(blank=True, max_length=100, verbose_name='Note')),
                ('coat', models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'abnormal', 'Abnormal')], max_length=10, verbose_name='Coat')),
                ('coat_note', models.CharField(blank=True, max_length=100, verbose_name='Note')),
                ('skin', models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'abnormal', 'Abnormal')], max_length=10, verbose_name='Skin')),
                ('skin_note', models.CharField(blank=True, max_length=100, verbose_name='Note')),
                ('musculoskeletal_system', models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'abnormal', 'Abnormal')], max_length=10, verbose_name='Musculoskeletal System')),
                ('musculoskeletal_system_note', models.CharField(blank=True, max_length=100, verbose_name='Note')),
                ('central_and_peripheral_nervous_system', models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'abnormal', 'Abnormal')], max_length=10, verbose_name='Central and Peripheral Nervous Systems')),
                ('central_and_peripheral_nervous_system_note', models.CharField(blank=True, max_length=100, verbose_name='Note')),
                ('additional_findings', models.TextField(blank=True, verbose_name='Note')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Animal', verbose_name="Animal's Name")),
            ],
            options={
                'ordering': ('date',),
                'verbose_name': 'Examination',
                'verbose_name_plural': 'Examinations',
            },
        ),
        migrations.CreateModel(
            name='ExaminationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Examination',
                'verbose_name_plural': 'Examinations',
            },
        ),
        migrations.AddField(
            model_name='examination',
            name='examination_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physical_examination.ExaminationType', verbose_name='Type'),
        ),
    ]
