# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-05 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Indication',
                'verbose_name_plural': 'Indications',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=150)),
                ('commercial_name', models.CharField(blank=True, max_length=150)),
                ('use', models.CharField(blank=True, choices=[('human', 'Human'), ('pediatric', 'Human pediatric'), ('vet', 'Vet')], default=None, max_length=10)),
                ('value', models.CharField(max_length=10)),
                ('value_for', models.CharField(max_length=10)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.Classification')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.Group')),
                ('indication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.Indication')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.Manufacturer')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ('generic_name',),
            },
        ),
        migrations.CreateModel(
            name='MedicineDosage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_from', models.CharField(max_length=10)),
                ('value_to', models.CharField(blank=True, max_length=10)),
                ('value_for', models.CharField(default=1, max_length=10)),
                ('frequency', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Medicine dosage',
                'verbose_name_plural': 'Medicines dosage',
                'ordering': ('medicine',),
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Presentation',
                'verbose_name_plural': 'Presentations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'Systems',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='Abbreviation')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.System', verbose_name='System')),
            ],
            options={
                'verbose_name': 'Unit of measurement',
                'verbose_name_plural': 'Units of measurement',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='medicinedosage',
            name='duration_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosage_period', to='medicine.UnitOfMeasurement'),
        ),
        migrations.AddField(
            model_name='medicinedosage',
            name='frequency_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosage_periodicity', to='medicine.UnitOfMeasurement'),
        ),
        migrations.AddField(
            model_name='medicinedosage',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.Medicine'),
        ),
        migrations.AddField(
            model_name='medicinedosage',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Specie'),
        ),
        migrations.AddField(
            model_name='medicinedosage',
            name='value_for_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosage_value_for_unit', to='medicine.UnitOfMeasurement'),
        ),
        migrations.AddField(
            model_name='medicinedosage',
            name='value_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosage_value_unit', to='medicine.UnitOfMeasurement'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.Presentation'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='value_for_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_value_for_unit', to='medicine.UnitOfMeasurement'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='value_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_value_unit', to='medicine.UnitOfMeasurement'),
        ),
    ]
