# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-02 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicinedosage',
            unique_together=set([('medicine', 'specie')]),
        ),
    ]
